version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8080:8080
    tty: true
    init: true
    volumes:
      - ./:/var/www:cached
    command: sleep infinity
    networks:
      net1:
        ipv4_address: 192.168.10.20
networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
